### ISSUE TITLE
Tests do not work out-of-box [Solution Provided]

### ISSUE THREAD

**Issue by rex** [technicalpickles/jeweler#266]
**Debug Info:**
Ruby `2.1.1`
Jeweler `2.0.1`
## Problem

Installed the Jeweler gem again, having recently upgraded to Ruby `2.1.1`. Wanted to try to run the tests so I could run `rake install`, things blew up. 

```
$ rake test
/Users/pierce/.rbenv/versions/2.1.1/bin/ruby -I"lib:lib:test" -I"/Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib" "/Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb" "test/**/test_*.rb"
method load_adapter is deprecated. use load_profile instead
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/2.1.0/test/unit.rb:1:in `require'
  /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/2.1.0/test/unit.rb:1:in `<top (required)>'
  /Users/pierce/GitHub/gems/ssh-builder/test/helper.rb:26:in `require'
  /Users/pierce/GitHub/gems/ssh-builder/test/helper.rb:26:in `<top (required)>'
  /Users/pierce/GitHub/gems/ssh-builder/test/test_ssh-builder.rb:1:in `require'
  /Users/pierce/GitHub/gems/ssh-builder/test/test_ssh-builder.rb:1:in `<top (required)>'
  /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:10:in `require'
  /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
  /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:9:in `each'
  /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:9:in `block in <main>'
  /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:4:in `select'
  /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:4:in `<main>'
MiniTest::Unit::TestCase is now Minitest::Test. From /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/2.1.0/test/unit/testcase.rb:8:in `<module:Unit>'
/Users/pierce/.rbenv/versions/2.1.1/lib/ruby/2.1.0/test/unit.rb:676:in `<class:Runner>': undefined method `_run_suite' for class `Test::Unit::Runner' (NameError)
    from /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/2.1.0/test/unit.rb:261:in `<module:Unit>'
    from /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/2.1.0/test/unit.rb:15:in `<module:Test>'
    from /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/2.1.0/test/unit.rb:7:in `<top (required)>'
    from /Users/pierce/GitHub/gems/ssh-builder/test/helper.rb:26:in `require'
    from /Users/pierce/GitHub/gems/ssh-builder/test/helper.rb:26:in `<top (required)>'
    from /Users/pierce/GitHub/gems/ssh-builder/test/test_ssh-builder.rb:1:in `require'
    from /Users/pierce/GitHub/gems/ssh-builder/test/test_ssh-builder.rb:1:in `<top (required)>'
    from /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:10:in `require'
    from /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
    from /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:9:in `each'
    from /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:9:in `block in <main>'
    from /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:4:in `select'
    from /Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test" -I"/Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib" "/Users/pierce/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```
## Solution

Modified the following files as indicated:

> `test/helper.rb`

``` ruby
SimpleCov.configure do
  clean_filters
  # load_adapter 'test_frameworks'
  load_profile 'test_frameworks'
end
```

``` ruby
# require 'test/unit'
require 'minitest/autorun'
require 'shoulda'
```

``` ruby
# class Test::Unit::TestCase
# end
class MiniTest::Test
end

MiniTest.autorun
```

> `test/test_{GEM_NAME}.rb`

``` ruby
# class Test{GEM_NAME} < Test::Unit::TestCase
class Test{GEM_NAME} < MiniTest::Test
```
## Conclusion

It fired right up! I hope this helps someone else who is stuck on that set of errors!
- Pierce

**Comment by jonatasrancan** [comment]
Helped me too @rex.

**Comment by rex** [comment]
Awesome! Glad I could help @tebemis @jonatasrancan :shipit:
