### ISSUE TITLE
Jeweler crashes when gem is a submodule

### ISSUE THREAD

**Issue by DavidHuie** [technicalpickles/jeweler#271]
```
[nbdev@davidhuie-8 reactorc (01f294b)]$ rake gemspec
rake aborted!
NameError: uninitialized constant Jeweler::Git
/Users/nbdev/.rvm/gems/ruby-2.1.2@reactorc/gems/jeweler-2.0.1/lib/jeweler.rb:40:in `initialize'
/Users/nbdev/.rvm/gems/ruby-2.1.2@reactorc/gems/jeweler-2.0.1/lib/jeweler/tasks.rb:52:in `new'
/Users/nbdev/.rvm/gems/ruby-2.1.2@reactorc/gems/jeweler-2.0.1/lib/jeweler/tasks.rb:52:in `jeweler'
/Users/nbdev/.rvm/gems/ruby-2.1.2@reactorc/gems/jeweler-2.0.1/lib/jeweler/tasks.rb:82:in `block in define'
/Users/nbdev/.rvm/gems/ruby-2.1.2@reactorc/bin/ruby_executable_hooks:15:in `eval'
/Users/nbdev/.rvm/gems/ruby-2.1.2@reactorc/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => gemspec => gemspec:generate => version_required
(See full trace by running task with --trace)
```

**Comment by flajann2** [comment]
I know you posted this a couple of years ago, but is this still an issue today? Thanks for your response.
