### ISSUE TITLE
Conflict with [remote "origin"] config in ~/.gitconfig

### ISSUE THREAD

**Issue by pixelastic** [technicalpickles/jeweler#287]
Hello,

When I try to start a new gem project with `jeweler hello-world`, I'm greeted with the following message:

```
Encountered an error while adding origin remote. Maybe you have some weird settings in ~/.gitconfig?
/home/tim/.rvm/gems/ruby-2.2.3/gems/git-1.3.0/lib/git/lib.rb:937:in `command': git '--git-dir=/tmp/hello-world/.git' '--work-tree=/tmp/hello-world' remote 'add' '--' 'origin' 'git@github.com:pixelastic/hello-world.git'  2>&1:fatal: remote origin already exists. (Git::GitExecuteError)
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/git-1.3.0/lib/git/lib.rb:688:in `remote_add'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/git-1.3.0/lib/git/base.rb:371:in `add_remote'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/jeweler-2.0.1/lib/jeweler/generator.rb:279:in `block in create_version_control'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/jeweler-2.0.1/lib/jeweler/generator.rb:258:in `chdir'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/jeweler-2.0.1/lib/jeweler/generator.rb:258:in `create_version_control'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/jeweler-2.0.1/lib/jeweler/generator.rb:129:in `run'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/jeweler-2.0.1/lib/jeweler/generator/application.rb:34:in `run!'
        from /home/tim/.rvm/gems/ruby-2.2.3/gems/jeweler-2.0.1/bin/jeweler:9:in `<top (required)>'
        from /home/tim/.rvm/gems/ruby-2.2.3/bin/jeweler:23:in `load'
        from /home/tim/.rvm/gems/ruby-2.2.3/bin/jeweler:23:in `<main>'
        from /home/tim/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
        from /home/tim/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

```

I do have something related to the `origin` remote in my `~/.gitconfig`:

```
[remote "origin"]
  prune = true
```
(This allow [auto pruning of deleted remote branches when doing a pull](http://stackoverflow.com/questions/18308535/automatic-prune-with-git-fetch-or-pull))

Still, `jeweler` seems to be choking on it because it is trying to create a remote that already exists. Removing the config from my `.gitconfig` lets me use the gem correctly.

I'm using git v2.8.0.rc1

**Comment by flajann2** [comment]
Thanks for this submission. I will take a look at it shortly.
