### ISSUE TITLE
Heads up: possible issue with bundler 1.13.0

### ISSUE THREAD

**Issue by francisluong** [technicalpickles/jeweler#289]
```
[jenkins@build-2 ddi-rest-client]$ rake gemspec --trace
** Invoke gemspec (first_time)
** Invoke gemspec:generate (first_time)
** Invoke version_required (first_time)
** Execute version_required
rake aborted!
NoMethodError: undefined method `dependencies_for' for #<Bundler::Runtime:0x00000001485a98>
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/jeweler-2.0.1/lib/jeweler/specification.rb:73:in `block in set_jeweler_defaults'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/jeweler-2.0.1/lib/jeweler/specification.rb:41:in `chdir'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/jeweler-2.0.1/lib/jeweler/specification.rb:41:in `set_jeweler_defaults'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/jeweler-2.0.1/lib/jeweler.rb:37:in `initialize'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/jeweler-2.0.1/lib/jeweler/tasks.rb:52:in `new'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/jeweler-2.0.1/lib/jeweler/tasks.rb:52:in `jeweler'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/jeweler-2.0.1/lib/jeweler/tasks.rb:82:in `block in define'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:248:in `call'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:248:in `block in execute'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:243:in `each'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:243:in `execute'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/home/jenkins/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:207:in `each'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:207:in `invoke_prerequisites'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
/home/jenkins/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:209:in `block in invoke_prerequisites'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:207:in `each'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:207:in `invoke_prerequisites'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:186:in `block in invoke_with_call_chain'
/home/jenkins/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/task.rb:173:in `invoke'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/application.rb:150:in `invoke_task'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/application.rb:106:in `each'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/application.rb:106:in `block in top_level'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/application.rb:115:in `run_with_threads'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/application.rb:100:in `top_level'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/application.rb:78:in `block in run'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/application.rb:176:in `standard_exception_handling'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/lib/rake/application.rb:75:in `run'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/gems/rake-11.1.1/bin/rake:33:in `<top (required)>'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/bin/rake:23:in `load'
/home/jenkins/.rvm/gems/ruby-2.0.0-p598/bin/rake:23:in `<main>'
Tasks: TOP => gemspec => gemspec:generate => version_required
[jenkins@build-2 ddi-rest-client]$ bundler -v
Bundler version 1.13.0
```

Works fine before bundler-1.13.0:
```
[jenkins@build-2 ddi-rest-client]$ gem uninstall bundler

Select gem to uninstall:
 1. bundler-1.13.0
 2. bundler-1.10.6
 3. All versions
> 1
Successfully uninstalled bundler-1.13.0


[jenkins@build-2 ddi-rest-client]$ rake gemspec
Generated: ddi-rest-client.gemspec
ddi-rest-client.gemspec is valid.
```

**Comment by flajann2** [comment]
Just updated and release a new Gem. Should work fine with Bundler 1.13
