### ISSUE TITLE
NoMethodError: undefined method `dependencies_for' for #<Bundler::Runtime:0x007fa38389e1c0>

### ISSUE THREAD

**Issue by Deekor** [technicalpickles/jeweler#303]
First time using jeweler.

When running any rake command I get the error:

```
NoMethodError: undefined method `dependencies_for' for #<Bundler::Runtime:0x007fa38389e1c0>
Did you mean?  dependencies
/Users/Dee/.rvm/gems/ruby-2.3.1/gems/jeweler-2.0.1/lib/jeweler/specification.rb:73:in `block in set_jeweler_defaults'
/Users/Dee/.rvm/gems/ruby-2.3.1/gems/jeweler-2.0.1/lib/jeweler/specification.rb:41:in `chdir'
/Users/Dee/.rvm/gems/ruby-2.3.1/gems/jeweler-2.0.1/lib/jeweler/specification.rb:41:in `set_jeweler_defaults'
/Users/Dee/.rvm/gems/ruby-2.3.1/gems/jeweler-2.0.1/lib/jeweler.rb:37:in `initialize'
/Users/Dee/.rvm/gems/ruby-2.3.1/gems/jeweler-2.0.1/lib/jeweler/tasks.rb:52:in `new'
/Users/Dee/.rvm/gems/ruby-2.3.1/gems/jeweler-2.0.1/lib/jeweler/tasks.rb:52:in `jeweler'
/Users/Dee/.rvm/gems/ruby-2.3.1/gems/jeweler-2.0.1/lib/jeweler/tasks.rb:154:in `block (2 levels) in define'
/Users/Dee/.rvm/gems/ruby-2.3.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/Dee/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/Dee/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => version:write
(See full trace by running task with --trace)
```
I tried updating bundler to the latest version and am still encountering the error.

**Comment by tadman** [comment]
This was [fixed before](https://github.com/technicalpickles/jeweler/issues/289), but it's back.

**Comment by infinite-monkeys** [comment]
@Deekor If you're new to jeweler, try juwelier.

@tadman I ran into this too, and found this opened issue.  I hate to say it, but I switched to juwelier (2.4.9) and the problem went away. Took a few minutes. I did patch the Rakefile for my gem to match the default juwelier-generated one.

**Comment by tadman** [comment]
[Juwelier](https://github.com/flajann2/juwelier) link for the lazy, like me.

Thanks for the recommendation. I really like the simplicity of Jeweler.
