### ISSUE TITLE
SecurityError: Insecure operation - file? in lib/jeweler/gemspec_helper.rb

### ISSUE THREAD

**Issue by JasonBarnabe** [technicalpickles/jeweler#304]
Trying to run `rake release` on https://github.com/tigrish/devise-i18n:

```
jason@jason-ThinkPad-T450:/www/devise-i18n$ ruby -v
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]
jason@jason-ThinkPad-T450:/www/devise-i18n$ gem -v
3.0.2
jason@jason-ThinkPad-T450:/www/devise-i18n$ rake release
Pushing master to origin
Generated: devise-i18n.gemspec
devise-i18n.gemspec is valid.
rake aborted!
SecurityError: Insecure operation - file?
/home/jason/.rvm/gems/ruby-2.6.0@devise-i18n/gems/jeweler-2.3.9/lib/jeweler/gemspec_helper.rb:59:in `file?'
/home/jason/.rvm/gems/ruby-2.6.0@devise-i18n/gems/jeweler-2.3.9/lib/jeweler/gemspec_helper.rb:59:in `block in normalize_files'
/home/jason/.rvm/gems/ruby-2.6.0@devise-i18n/gems/jeweler-2.3.9/lib/jeweler/gemspec_helper.rb:58:in `normalize_files'
/home/jason/.rvm/gems/ruby-2.6.0@devise-i18n/gems/jeweler-2.3.9/lib/jeweler/gemspec_helper.rb:26:in `to_ruby'
/home/jason/.rvm/gems/ruby-2.6.0@devise-i18n/gems/jeweler-2.3.9/lib/jeweler/gemspec_helper.rb:49:in `parse'
/home/jason/.rvm/gems/ruby-2.6.0@devise-i18n/gems/jeweler-2.3.9/lib/jeweler/commands/build_gem.rb:13:in `run'
/home/jason/.rvm/gems/ruby-2.6.0@devise-i18n/gems/jeweler-2.3.9/lib/jeweler.rb:88:in `build_gem'
/home/jason/.rvm/gems/ruby-2.6.0@devise-i18n/gems/jeweler-2.3.9/lib/jeweler/tasks.rb:98:in `block in define'
Tasks: TOP => release => gemcutter:release => build
(See full trace by running task with --trace)
```

**Comment by cbliard** [comment]
I just got a similar issue and provided a pull request to fix it. Can you test if that pull request works for you?

**Comment by JasonBarnabe** [comment]
Yes, it works with that change.
